
error => $%^

// single line comment
lit_dq_rule   = "literal" // single line comment
;
lit_sq_rule   // single line comment
	= 'literal';
set_rule      = {'s' 'e' 't'};
range_rule    = {'s'..'t'};
rule_one_of   = 'a' | 'b';
rule_sequnece = 'a', 'b';
group_rule    = ('a', 'b');
zero_or_one   = ?'b';
/*
 * Multi line comment
 */
zero_or_more  = *'b';
one_or_more   = +'b'; /* end of line comment */
n_to_m        = 1..2 'b';
n  /* inline comment */  = 3'b';
^
not_rule      = !'c';

#transitive_rule = '#';
~none_rule       = '~';


reference_rule = transitive_rule, range_rule
% 