// Example EBNF-like notation for the tokens/grammar of json (TO BE)

TOKENS
---------------------------------------------------------------------------------------------------

include "some token file.ebnf".


GRAMMAR
---------------------------------------------------------------------------------------------------

include "some grammar file.ebnf".

namespace json_grammar.

json					   : object or array or eof.

eof						   : not any.

key						   : string.
value					   : string or int or float or boolean or null or object or array.

key_value_pair			   : key, (drop) kv_separator, value.

transitive key_value_list  : key_value_pair, zero_or_more((drop) item_separator, key_value_pair).

object					   : (drop) scope_start, (drop) key_value_list, (drop) scope_end.

transtive array_item_list  : value, zero_or_more( (drop) item_separator, value).
array					   : (drop) array_start, (drop) array_item_list, (drop) array_end.


VALID EXAMPLES
---------------------------------------------------------------------------------------------------

key_value_pair:
	
	"\"key\": 123".

array: 

	"[]",
	"[ \"foo\" ]",
	"[ 1, 2, 3 ]",
	"[ [ "abc", 1, 2 ]]". 

INVALID EXAMPLES
---------------------------------------------------------------------------------------------------

array: 

	"[",
	"[ \"foo\"". 
