/* 
 * Simple EBNF notation for the tokens json
 */

#json_tokens	= *valid_token;

#valid_token	= json_token | white_space | unknown_token;

#json_token		= float | int | boolean | null | string | scope_start | scope_end | array_start | array_end | 
					kv_separator | item_separator;

~sign           = '+' | '-';
digit           = { '0'..'9' };
float           = int, '.', +digit, ?(('e' | 'E'), int);
int             = ?sign, +digit;

boolean         = 'true' | 'false';
null			= 'null';

// allow for both single - and double quoted strings
~sq_string_char = !'"', .;
~sq_string      = '"', *sq_string_char, '"';

~dq_string_char = !"'", .;
~dq_string      = "'", *dq_string_char, "'";

string			= sq_string | dq_string;

scope_start		= '{';
scope_end		= '}';

array_start		= '[';
array_end		= ']';

kv_separator	= ':';
item_separator	= ',';

~white_space	= { ' \t\r\n' };

// errors
unknown_token	= error "unknown token found." if *(!json_token, .);