// Autogenerated class using gg.parse.script.ScriptUtils.ExportNames.
// Strongly recommend to refrain from making changes in this class as they made be overwritten.
namespace gg.parse.argparser
{
   public static class ArgParserNames
   {
        public const string Letter = "letter";
        public const string Digit = "digit";
        public const string Minus = "minus";
        public const string Plus = "plus";
        public const string Sign = "sign";
        public const string Float = "float";
        public const string Int = "int";
        public const string SqStringChar = "sq_string_char";
        public const string SqString = "sq_string";
        public const string DqStringChar = "dq_string_char";
        public const string DqString = "dq_string";
        public const string String = "string";
        public const string Eof = "eof";
        public const string Space = "space";
        public const string WhiteSpace = "white_space";
        public const string PropertyToken = "property_token";
        public const string PropertyTokenList = "property_token_list";
        public const string Boolean = "boolean";
        public const string Null = "null";
        public const string Identifier = "identifier";
        public const string ScopeStart = "scope_start";
        public const string ScopeEnd = "scope_end";
        public const string ArrayStart = "array_start";
        public const string ArrayEnd = "array_end";
        public const string KvSeparator = "kv_separator";
        public const string ItemSeparator = "item_separator";
        public const string UnknownPropertyError = "unknown_property_error";
        public const string FileNameTokens = "file_name_tokens";
        public const string FileNameToken = "file_name_token";
        public const string BaseName = "base_name";
        public const string AllowedSymbols = "allowed_symbols";
        public const string ValidNameChar = "valid_name_char";
        public const string Drive = "drive";
        public const string Colon = "colon";
        public const string Period = "period";
        public const string ParentDir = "parent_dir";
        public const string DirectorySeparator = "directory_separator";
        public const string Quote = "quote";
        public const string ArgTokens = "arg_tokens";
        public const string ArgToken = "arg_token";
        public const string ArgKey = "arg_key";
        public const string ArgKeySwitch = "arg_key_switch";
        public const string ArgIdentifier = "arg_identifier";
        public const string UnknownArgToken = "unknown_arg_token";
        public const string Properties = "properties";
        public const string Key = "key";
        public const string Value = "value";
        public const string KeyValuePair = "key_value_pair";
        public const string KeyValueList = "key_value_list";
        public const string Object = "object";
        public const string ValueValuePair = "value_value_pair";
        public const string ValueValueList = "value_value_list";
        public const string Dictionary = "dictionary";
        public const string ArrayItemList = "array_item_list";
        public const string Array = "array";
        public const string Filename = "filename";
        public const string FilenameSequence = "filename_sequence";
        public const string AbsolutePath = "absolute_path";
        public const string PathPart = "path_part";
        public const string Path = "path";
        public const string PathChain = "path_chain";
        public const string Root = "root";
        public const string ArgOption = "arg_option";
        public const string ArgValue = "arg_value";
        public const string UnknownArgGrammar = "unknown_arg_grammar";
   }
}
