// Autogenerated class using gg.parse.script.ScriptUtils.ExportNames.
// Strongly recommend to refrain from making changes in this class as they made be overwritten.
namespace gg.parse.argparser
{
   public static class ArgParserNames
   {
        public static readonly string Letter = "letter";
        public static readonly string Digit = "digit";
        public static readonly string Minus = "minus";
        public static readonly string Plus = "plus";
        public static readonly string Sign = "sign";
        public static readonly string Float = "float";
        public static readonly string Int = "int";
        public static readonly string SqStringChar = "sq_string_char";
        public static readonly string SqString = "sq_string";
        public static readonly string DqStringChar = "dq_string_char";
        public static readonly string DqString = "dq_string";
        public static readonly string String = "string";
        public static readonly string Eof = "eof";
        public static readonly string Space = "space";
        public static readonly string WhiteSpace = "white_space";
        public static readonly string PropertyToken = "property_token";
        public static readonly string PropertyTokenList = "property_token_list";
        public static readonly string Boolean = "boolean";
        public static readonly string Null = "null";
        public static readonly string Identifier = "identifier";
        public static readonly string ScopeStart = "scope_start";
        public static readonly string ScopeEnd = "scope_end";
        public static readonly string ArrayStart = "array_start";
        public static readonly string ArrayEnd = "array_end";
        public static readonly string KvSeparator = "kv_separator";
        public static readonly string ItemSeparator = "item_separator";
        public static readonly string UnknownPropertyError = "unknown_property_error";
        public static readonly string FileNameTokens = "file_name_tokens";
        public static readonly string FileNameToken = "file_name_token";
        public static readonly string BaseName = "base_name";
        public static readonly string AllowedSymbols = "allowed_symbols";
        public static readonly string ValidNameChar = "valid_name_char";
        public static readonly string Drive = "drive";
        public static readonly string Colon = "colon";
        public static readonly string Period = "period";
        public static readonly string ParentDir = "parent_dir";
        public static readonly string DirectorySeparator = "directory_separator";
        public static readonly string Quote = "quote";
        public static readonly string ArgTokens = "arg_tokens";
        public static readonly string ArgToken = "arg_token";
        public static readonly string ArgKey = "arg_key";
        public static readonly string ArgKeySwitch = "arg_key_switch";
        public static readonly string ArgIdentifier = "arg_identifier";
        public static readonly string UnknownArgToken = "unknown_arg_token";
        public static readonly string Properties = "properties";
        public static readonly string Key = "key";
        public static readonly string Value = "value";
        public static readonly string KeyValuePair = "key_value_pair";
        public static readonly string KeyValueList = "key_value_list";
        public static readonly string Object = "object";
        public static readonly string ArrayItemList = "array_item_list";
        public static readonly string Array = "array";
        public static readonly string Filename = "filename";
        public static readonly string FilenameSequence = "filename_sequence";
        public static readonly string AbsolutePath = "absolute_path";
        public static readonly string PathPart = "path_part";
        public static readonly string Path = "path";
        public static readonly string PathChain = "path_chain";
        public static readonly string Root = "root";
        public static readonly string ArgOption = "arg_option";
        public static readonly string ArgValue = "arg_value";
        public static readonly string UnknownArgGrammar = "unknown_arg_grammar";
   }
}
