// Autogenerated class using gg.parse.script.ScriptUtils.ExportNames.
// Strongly recommend to refrain from making changes in this class as they made be overwritten.
namespace gg.parse.properties
{
   public static class PropertyFileNames
   {
        public const string Array = "array";
        public const string ArrayEnd = "array_end";
        public const string ArrayItemList = "array_item_list";
        public const string ArrayStart = "array_start";
        public const string Boolean = "boolean";
        public const string Dictionary = "dictionary";
        public const string Digit = "digit";
        public const string DqString = "dq_string";
        public const string DqStringChar = "dq_string_char";
        public const string Eof = "eof";
        public const string Float = "float";
        public const string Identifier = "identifier";
        public const string Int = "int";
        public const string ItemSeparator = "item_separator";
        public const string KvpList = "kvp_list";
        public const string KvpPair = "kvp_pair";
        public const string KvSeparator = "kv_separator";
        public const string Letter = "letter";
        public const string Minus = "minus";
        public const string MultiLineComment = "multi_line_comment";
        public const string Null = "null";
        public const string Plus = "plus";
        public const string Properties = "properties";
        public const string PropertyToken = "property_token";
        public const string PropertyTokenList = "property_token_list";
        public const string PropertyTokens = "property_tokens";
        public const string ScopeEnd = "scope_end";
        public const string ScopeStart = "scope_start";
        public const string Sign = "sign";
        public const string SingleLineComment = "single_line_comment";
        public const string Space = "space";
        public const string SqString = "sq_string";
        public const string SqStringChar = "sq_string_char";
        public const string String = "string";
        public const string Underscore = "underscore";
        public const string UnknownPropertyError = "unknown_property_error";
        public const string Value = "value";
        public const string WhiteSpace = "white_space";
   }
}
