// Autogenerated class using gg.parse.script.ScriptUtils.ExportNames.
// Strongly recommend to refrain from making changes in this class as they made be overwritten.
namespace gg.parse.calculator
{
   public static class CalculatorNames
   {
        public const string Addition = "addition";
        public const string AdditionErr = "addition_err";
        public const string AdditionOptions = "addition_options";
        public const string CalculatorTokens = "calculator_tokens";
        public const string Digit = "digit";
        public const string Div = "div";
        public const string Division = "division";
        public const string DivisionErr = "division_err";
        public const string DivisionOptions = "division_options";
        public const string Expression = "expression";
        public const string Group = "group";
        public const string GroupEnd = "group_end";
        public const string GroupErr = "group_err";
        public const string GroupStart = "group_start";
        public const string GroupVariations = "group_variations";
        public const string Minus = "minus";
        public const string MissingOperatorErr = "missing_operator_err";
        public const string Mult = "mult";
        public const string Multiplication = "multiplication";
        public const string MultiplicationErr = "multiplication_err";
        public const string MultOptions = "mult_options";
        public const string Number = "number";
        public const string Operation = "operation";
        public const string Plus = "plus";
        public const string Sign = "sign";
        public const string SubErr = "sub_err";
        public const string SubOptions = "sub_options";
        public const string Subtraction = "subtraction";
        public const string Term = "term";
        public const string UnaryOperation = "unary_operation";
        public const string UnknownExpression = "unknown_expression";
        public const string UnknownToken = "unknown_token";
        public const string ValidToken = "valid_token";
        public const string WhiteSpace = "white_space";
   }
}
