// Autogenerated class using gg.parse.script.ScriptUtils.ExportTokens.
// Strongly recommend to refrain from making changes in this class as they made be overwritten.
namespace gg.parse.properties
{
   public static class PropertiesTokens
   {
        public const string ArrayEnd = "]";
        public const string ArrayStart = "[";
        public const string BoolFalse = "false";
        public const string BoolTrue = "true";
        public const string ItemSeparator = ",";
        public const string KvSeparatorColon = ":";
        public const string KvSeparatorEquals = "=";
        public const string Minus = "-";
        public const string MultiLineCommentEnd = "*/";
        public const string MultiLineCommentStart = "/*";
        public const string Null = "null";
        public const string Plus = "+";
        public const string ScopeEnd = "}";
        public const string ScopeStart = "{";
        public const string SingleLineCommentStart = "//";
        public const string Space = " ";
        public const string Underscore = "_";
   }
}
